In [1]:
import numpy as np

print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [3]:
L = range(1000)
%timeit [i**2 for i in L]

478 µs ± 8.46 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
a = np.arange(1000)
%timeit a**2

1.77 µs ± 17.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [7]:
#1D Array
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [8]:
#print dimension
a.ndim

1

In [9]:
#shape
a.shape

(4,)

In [15]:
# 2-D, 3-D

b = np.array([[0,1,2,3],[4,5,6,7]])
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
b.ndim

2

In [12]:
b.shape

(2, 4)

In [13]:
len(b) 

2

In [16]:
b = np.arange(1,10,2) #start, end, step size
b

array([1, 3, 5, 7, 9])

In [18]:
#using linspace
a = np.linspace(0,1,6) #start,end, number of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [19]:
#common arrays
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
#identity matrix in which diagonals should be 1
np.eye(3)  #I3*3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(3,2) # 3 is number of rows, 2 is number of columns

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [27]:
#create array using diag function
a = np.diag([1,2,3,4])  #construct a diagonal array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [5]:
#create array using diag function
import numpy as np
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [6]:
np.diag(a) #Extract diagonal

array([1, 2, 3, 4])

In [9]:
#create array using random
#create an array of the given shape and populate it with random 
a = np.random.rand(4)
a

array([0.19749681, 0.16944938, 0.72959493, 0.80007303])

In [10]:
a = np.arange(10)
a.dtype

dtype('int32')

In [12]:
a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#complex numbers
d = np.array([1+2j, 2+4j])
print(d.dtype)

complex128


In [17]:
#accessing array
a = np.arange(10)
print(a[5])

5


In [18]:
a[1:8:2]

array([1, 3, 5, 7])

In [19]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [2]:
#----------13th april-------
import numpy as np

a = np.array([1,2,3,4]) #creating an array
a+1

array([2, 3, 4, 5])

In [3]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [5]:
b = np.ones(4)+1
b

array([2., 2., 2., 2.])

In [6]:
b = np.ones(4)+1
a-b

array([-1.,  0.,  1.,  2.])

In [7]:
a*b

array([2., 4., 6., 8.])

In [8]:
# Matrix Multiplication

c = np.diag([1,2,3,4])

c*c

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [22]:
  #Comparison
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
a == b

array([False,  True, False,  True])

In [23]:
a>b

array([False, False,  True, False])

In [24]:
#array wise comparisons
a = np.array([1,2,3,4])
b = np.array([3,2,4,5])
c = np.array([1,2,3,4])

np.array_equal(a,b)

False

In [25]:
np.array_equal(a,c)

True

In [3]:
 #===========Logical Operations=================
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)

np.logical_or(a,b)

array([ True,  True,  True, False])

In [4]:
np.logical_and(a,b)

array([ True, False, False, False])

In [6]:
#=========Transcendental functions=========
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [7]:
np.log(a)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [8]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [9]:
#=========Shape mismatch=========
a = np.arange(4)
a+np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [4]:
#=================Basic reductions==============
import numpy as np
x = np.array([1,2,3,4])
np.sum(x)

10

In [6]:
#sum by rows and by columns
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [7]:
x.sum(axis=0) #columns first dimension

array([3, 3])

In [8]:
x.sum(axis=1) #rows (second dimension)

array([2, 4])

In [9]:
#==========Other reductions=========
x = np.array([1,3,2])
x.min()

1

In [10]:
x.max()

3

In [11]:
x.argmin() #index of minimum element

0

In [12]:
x.argmax()

1

In [13]:
#============Logical operations==========
np.all([True, True, False])

False

In [14]:
np.any([True, False, False])

True

In [15]:
a = np.zeros((50,50))
np.any(a!=0)

False

In [16]:
np.all(a==a)

True

In [17]:
#===comparisons of array in a single line without using any loop=======
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
((a<=b) & (b<=c)).all()

True

In [18]:
#=======Statistics==========
x = np.array([1,2,3,1])
y = np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [19]:
np.median(x)

1.5

In [20]:
np.median(y, axis=-1) #last axis

array([2., 5.])

In [21]:
x.std() #full population standard deviation

0.82915619758885

In [3]:
data = loadXls("demo.xls")

NameError: name 'loadXls' is not defined

In [83]:
import pandas as pd

z = pd.pandas.read_excel(r'C:\Users\user\Downloads\PythonWorkspace\iPythonNotebook\demo.xlsx', sheet_name='Sheet1')
df=z.values
df

array([[ 6, 22, 38],
       [ 7, 23, 39],
       [ 8, 24, 40],
       [ 9, 25, 41],
       [10, 26, 42],
       [11, 27, 43],
       [12, 28, 44],
       [13, 29, 45],
       [14, 30, 46],
       [15, 31, 47],
       [16, 32, 48],
       [17, 33, 49],
       [18, 34, 50],
       [19, 35, 51],
       [20, 36, 52]], dtype=int64)

In [35]:
df.sum(axis=1)


array([ 66,  69,  72,  75,  78,  81,  84,  87,  90,  93,  96,  99, 102,
       105, 108], dtype=int64)

In [36]:
df.std(axis=0)

array([4.3204938, 4.3204938, 4.3204938])

In [37]:
import numpy as np
np.argmax(df,axis=1)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [85]:
#i=5
j=2
print(j)
#df[i,j] = 100
#for i in df:
    #df[i,j] = 100
   # print(i)

df[1::2,2]=50
df
    



2


array([[ 6, 22, 38],
       [ 7, 23, 50],
       [ 8, 24, 40],
       [ 9, 25, 50],
       [10, 26, 42],
       [11, 27, 50],
       [12, 28, 44],
       [13, 29, 50],
       [14, 30, 46],
       [15, 31, 50],
       [16, 32, 48],
       [17, 33, 50],
       [18, 34, 50],
       [19, 35, 50],
       [20, 36, 52]], dtype=int64)